name: Build and release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Get tag
        uses: olegtarasov/get-tag@v2
        id: tagName

      - name: Get time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Build (tun)
        uses: crazy-max/ghaction-xgo@v1.6.1
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        with:
          xgo_version: latest
          go_version: 1.17
          dest: dist
          prefix: proxypool
          targets: linux/amd64,linux/386,linux/arm-5,linux/arm-7,linux/arm64,linux/mipsle,linux/s390x,darwin-10.12/amd64,darwin-10.12/arm64,windows-6.0/amd64,windows-6.0/386
          ldflags: -w -s -X main.appVersion=${{ env.GIT_TAG_NAME }} -X main.appCommit=${{ github.sha }} -X main.appDate=${{ env.TIME }}
          pkg: cmd

      - name: Upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/proxypool-linux-amd64
            ./dist/proxypool-linux-386
            ./dist/proxypool-linux-arm-5
            ./dist/proxypool-linux-arm-7
            ./dist/proxypool-linux-arm64
            ./dist/proxypool-linux-mipsle
            ./dist/proxypool-linux-s390x
            ./dist/proxypool-darwin-10.12-amd64
            ./dist/proxypool-darwin-10.12-arm64
            ./dist/proxypool-windows-6.0-amd64.exe
            ./dist/proxypool-windows-6.0-386.exe

